id: P007078
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8584
  title: འཇམ་མགོན་ཆོས་ཀྱི་རྒྱལ་པོ་ཙོང་ཁ་པ་ཆེན་པོའི་རྣམ་ཐར།
  author: ''
  volumes:
    bd0179c2a7944618860f632bf02c7762:
      image_group_id: I1KG8599
      title: ''
      volume_number: 1
      total_pages: 528
ebook_metadata:
  title: འཇམ་མགོན་ཆོས་ཀྱི་རྒྱལ་པོ་ཙོང་ཁ་པ་ཆེན་པོའི་རྣམ་ཐར།
  author: ''
  sku: P007078
  cover: cover.jpg
  layers:
  - pagination
