id: I0AECA13E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T20:40:26+00:00'
last_modified: '2022-06-09T04:38:05.170264+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8584
  title: འཇམ་མགོན་ཆོས་ཀྱི་རྒྱལ་པོ་ཙོང་ཁ་པ་ཆེན་པོའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F748:
      image_group_id: I1KG8599
      title: Volume 1 of 'jam mgon chos kyi rgyal po tsong kha pa chen po'i rnam thar/
      total_pages: 528
      order: 1
      base_file: F748.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
